services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  eurekaserver:
    container_name: eurekaserver
    build: ./eurekaserver
    ports:
      - "8761:8761"
    expose:
      - "8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 3
  client:
    container_name: client
    build: ./client
    ports:
      - "8081:8081"
    expose:
      - "8081"

    depends_on:
      eurekaserver:
        condition: service_healthy
      mysql:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/clientservicedb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      DISCOVERY_SERVICE_URL: http://eurekaserver:8761/eureka/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 3


  voiture:
    container_name: voiture
    build: ./voiture
    ports:
      - "8082:8082"
    expose:
      - "8082"

    depends_on:
      eurekaserver:
        condition: service_healthy
      mysql:
        condition: service_started
      client:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/carservicedb?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      DISCOVERY_SERVICE_URL: http://eurekaserver:8761/eureka/
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 3

  gateway:
    container_name: gateway
    build: ./gateway
    ports:
      - "8888:8888"
    expose:
      - "8888"
    depends_on:
      eurekaserver:
        condition: service_healthy
    environment:
      DISCOVERY_SERVICE_URL: http://eurekaserver:8761/eureka/


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8090:80"


